2024-03-21 16:34:38,310 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 16:35:10,776 - root - INFO - Caught an unexpected exception: 'NoneType' object has no attribute 'group',

2024-03-21 16:37:28,370 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 16:37:34,494 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:06.

2024-03-21 16:55:44,257 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 16:55:51,699 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:07.

2024-03-21 16:57:05,365 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 16:57:10,711 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:05.

2024-03-21 16:59:00,060 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 16:59:05,390 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:05.

2024-03-21 17:04:42,565 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 17:04:48,282 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:06.

2024-03-21 17:47:45,927 - root - INFO - Cleaning start, Batch_id:2019

2024-03-21 17:47:51,412 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:05.

2024-03-22 18:21:27,629 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:21:28,005 - root - INFO - Caught an unexpected exception: 'list' object has no attribute 'split',

2024-03-22 18:22:29,422 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:22:29,823 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:23:30,084 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:23:30,454 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:25:59,770 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:26:00,154 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:27:00,009 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:27:00,424 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:27:17,725 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:27:18,153 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:28:48,558 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:28:48,952 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:29:49,327 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:29:49,728 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:31:40,082 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:31:40,483 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:34:27,349 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:34:27,730 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:35:47,860 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:35:48,270 - root - INFO - Caught an unexpected exception: "None of [Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n       nan, nan],\n      dtype='float64')] are in the [columns]",

2024-03-22 18:39:51,358 - root - INFO - Cleaning start, Batch_id:2019

2024-03-22 18:39:51,807 - root - INFO - Caught an unexpected exception: save_progress() missing 1 required positional argument: 'year',

2024-03-27 21:06:00,876 - root - INFO - Cleaning start, Batch_id:2019

2024-03-27 21:06:00,883 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:00:00.

2024-03-27 21:06:19,140 - root - INFO - Cleaning start, Batch_id:2019

2024-03-27 21:08:18,576 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:01:59.

2024-04-03 18:30:14,051 - root - INFO - Cleaning start, Batch_id:2019

2024-04-03 18:34:29,012 - root - INFO - 50 Batch Completed. Processing:100%.[ 00:04:15/00:04:15, 196.08it/s ]

2024-04-03 18:34:29,014 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:04:15.

2024-04-03 20:13:16,524 - root - INFO - Cleaning start, Batch_id:2019

2024-04-03 20:13:20,531 - root - INFO - Caught an unexpected exception: "['Ô­ÎÄ'] not in index",

2024-04-03 20:15:02,717 - root - INFO - Cleaning start, Batch_id:2019

2024-04-03 20:15:39,124 - root - INFO - Caught an unexpected exception: expected string or bytes-like object, got 'float',

2024-04-03 20:16:33,097 - root - INFO - Cleaning start, Batch_id:2019

2024-04-03 20:18:47,275 - root - INFO - Cleaning start, Batch_id:2019

2024-04-03 20:19:40,775 - root - INFO - Network Error Occured: mongo.fqyai.cn:27017: [Errno 11001] getaddrinfo failed (configured timeouts: connectTimeoutMS: 20000.0ms),

2024-04-03 20:21:43,748 - root - INFO - Cleaning start, Batch_id:2019

2024-04-03 20:24:59,728 - root - INFO - 50 Batch Completed. Processing:100%.[ 00:03:16/00:03:16, 255.1it/s ]

2024-04-03 20:24:59,728 - root - INFO - WS_2019 CLeaning Completed. Time-Consuming: 00:03:16.

